apiVersion: v1
kind: Secret
metadata: 
   name: dbsecret
type: Opaque
data:
   MYSQL_DATABASE: ZnVuZG9vZGI=
   MYSQL_PASSWORD: ZnVuZG9vMTIz
   MYSQL_ROOT_PASSWORD: ZnVuZG9vMTIz
   MYSQL_USER: ZnVuZG9v



