apiVersion: v1
kind: Pod
metadata: 
   name: mysql
   labels:
    app: chatdb
spec:
  containers:
  - name: chatdb
    image: mysql/mysql-server
    envFrom:
      - secretRef: 
          name: dbsecret
    ports:
      - containerPort: 3306