apiVersion: v1
kind: Pod
metadata: 
   name: mysql
   spec:
      containers:
      - name: chatweb
        image: mysql/mysql-server
        envFrom:
          - secretRef: 
              name: dbsecret
        ports: 
         - containerPort: 3306